Repository osamhack2020/Cloud_BlurPencil_GonNyong4, pull requests merged in 2020-10, with the labels that each got.

#2 ADD : Save upload img and user data
  .gitignore
  server/routes/upload.js
  server/schemas/user.js
  server/schemas/work.js
  server/tempUploads/1601709387765.png
  server/tempUploads/1601709431630.png
  server/tempUploads/1601709736316.png
  server/tempUploads/1602076125221.jpg
  server/tempUploads/1602227002986.jpg
  server/tempUploads/1602334194107.jpg
  server/tempUploads/1602499526539.jpeg
Labels: enhancement

#4 UPDATE : Users login updatedAt & duplicate register
  server/routes/users.js
Labels: improve

#6 ADD : GET user data & PUT user password
  server/routes/users.js
Labels: enhancement

#10 ADD : Delete user & Forgot password(temp)
  client/src/components/SelectPage.vue
  server/app.js
  server/package-lock.json
  server/package.json
  server/routes/users.js
  server/schemas/user.js
Labels: API, enhancement

#11 Show Work Datas
  client/src/main.js
  client/src/views/Main.vue
  server/app.js
  server/routes/works.js
  server/tempUploads/1601804681139.png
  server/tempUploads/1601805185534.png
  server/tempUploads/1601806490932.jpg
  server/tempUploads/1601821381792.jpg
  server/tempUploads/1601993765823.jpg
  server/tempUploads/1602056742588.jpg
  server/tempUploads/1602075605096.jpg
  server/tempUploads/1602075619994.jpg
  server/tempUploads/1602075863904.jpg
  server/tempUploads/1602176572082.jpg
  server/tempUploads/1602176589374.jpg
  server/tempUploads/1602913578344.jpg
Labels: enhancement

#16 ADD: test_client.html and show_bbox
  logo_detection/app.py
  logo_detection/model.py
  logo_detection/test_client.html
  logo_detection/test_imgs/icis.jpg
  logo_detection/test_imgs/icis2.jpg
  logo_detection/test_imgs/subway.jpg
  logo_detection/test_imgs/taehoo.jpg
  logo_detection/test_imgs/th.jpg
  logo_detection/utils.py
Labels: API

#19 Show Recently Worked list
  client/src/views/Main.vue
  server/routes/works.js
Labels: API, 개선

#22 UPDATE Several designs & ADD function
  client/src/assets/style.css
  client/src/components/Login.vue
  client/src/components/SelectPage.vue
  client/src/views/Dashboard.vue
  client/src/views/Home.vue
  client/src/views/Profile.vue
  server/routes/upload.js
Labels: 질문

#21 ADD png file support, predict parameters
  .gitignore
  logo_detection/app.py
  logo_detection/config.py
  logo_detection/get_pretrained.py
  logo_detection/get_pth.py
  logo_detection/model.py
  logo_detection/test_client.py
  logo_detection/test_imgs/cafe.png
  logo_detection/test_imgs/goblin.png
  logo_detection/test_imgs/sth.png
  logo_detection/test_imgs/subway2.png
  logo_detection/test_imgs/tehking.png
  logo_detection/utils.py
Labels: API

#24 ADD : Remove worked file & Download worked file
  client/src/views/Main.vue
  server/routes/works.js
  server/tempUploads/1602499526539.jpeg
  server/tempUploads/1602913578344.jpg
Labels: API, 기능 추가

#25 Landing page design improve
  client/src/assets/style.css
  client/src/images/066.png
  client/src/views/Home.vue
Labels: 개선, 질문

#26 FIX functions when user use
  client/src/components/Login.vue
  client/src/components/SelectPage.vue
  client/src/views/Main.vue
  client/src/views/Profile.vue
Labels: 개선, 질문

#27 Design Upload UI
  client/src/components/SelectPage.vue
  client/src/components/UploadComponent.vue
  client/src/images/image-upload.svg
Labels: 개선

#31 Dashboard Nav design
  client/public/favicon.ico
  client/public/index.html
  client/src/App.vue
  client/src/assets/style.css
  client/src/components/Login.vue
  client/src/components/SelectPage.vue
  client/src/components/UploadComponent.vue
  client/src/images/check.svg
  client/src/images/dashboard.svg
  client/src/images/dashboard_hov.svg
  client/src/images/sign-out.svg
  client/src/images/uncheck.svg
  client/src/views/Dashboard.vue
  client/src/views/Home.vue
  client/src/views/Main.vue
  package-lock.json
  package.json
Labels: 개선

#30 ADD /predict paramters
  logo_detection/app.py
  logo_detection/config.py
  logo_detection/get_pretrained.py
  logo_detection/index.html
  logo_detection/model.py
  logo_detection/test_clients/test_all.html
  logo_detection/test_clients/test_blur.html
  logo_detection/test_clients/test_client.html
  logo_detection/test_clients/test_client.py
  logo_detection/utils.py
Labels: API

#33 Send Uploaded file -> logo_detection
  client/src/components/UploadComponent.vue
  client/src/images/sync.svg
  client/src/views/Dashboard.vue
  client/vue.config.js
  server/tempUploads/1603522043052.jpg
  server/tempUploads/1603605055803.jpg
Labels: 기능 추가

#35 Numerically adjustable : Upload Component
  client/src/assets/style.css
  client/src/components/UploadComponent.vue
  client/src/views/Dashboard.vue
Labels: 개선, 기능 추가

#38 FIX: fixed bug in /blur API and its example client
  logo_detection/app.py
  logo_detection/test_clients/test_blur.html
Labels: API, 버그

#40 Show Filtered image
  client/package-lock.json
  client/public/index.html
  client/src/components/UploadComponent.vue
  client/src/main.js
  client/src/views/Dashboard.vue
  server/tempUploads/1603605055803.jpg
Labels: 기능 추가

#41 Upload Dashboard
  client/src/components/UploadComponent.vue
  client/src/images/186.png
  client/src/images/ZombieingDoodle.png
  client/src/views/Main.vue
  server/routes/upload.js
  server/schemas/work.js
  server/tempUploads/1603871611204.jpg
Labels: 개선, 기능 추가

#42 Upload
  client/src/components/SelectPage.vue
  client/src/images/logo(125x125).png
  client/src/images/logo(250x250).png
  client/src/views/Home.vue
  client/src/views/Main.vue
  license.md
  readme.md
Labels: 개선

#44 ADD : Folder | Share
  client/src/components/FolderData.vue
  client/src/components/Login.vue
  client/src/components/SelectPage.vue
  client/src/components/WorkData.vue
  client/src/images/current.svg
  client/src/images/current_hov.svg
  client/src/images/share.svg
  client/src/router/index.js
  client/src/views/Main.vue
  client/src/views/Recent.vue
  server/app.js
  server/routes/folders.js
  server/routes/users.js
  server/routes/works.js
  server/schemas/folder.js
  server/schemas/work.js
  server/tempUploads/1603966340605.jpg
Labels: API, 개선, 기능 추가

#49 Update Landing page
  client/src/images/icons/check-circle.svg
  client/src/views/Home.vue
Labels: 개선
